ALTER TABLE "Kot" ADD COLUMN IF NOT EXISTS "station" TEXT DEFAULT 'KITCHEN';
ALTER TABLE "MenuCategory" ADD COLUMN IF NOT EXISTS "station" TEXT DEFAULT 'KITCHEN';
UPDATE "Kot" SET station = 'KITCHEN' WHERE station IS NULL;
UPDATE "MenuCategory" SET station = 'KITCHEN' WHERE station IS NULL;